# Generated by Django 5.2.5 on 2025-08-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='devise',
            field=models.CharField(choices=[('USD', 'Dollar américain'), ('CDF', 'Franc congolais'), ('EUR', 'Euro')], default='CDF', max_length=3),
        ),
    ]
