# Generated by Django 5.2.5 on 2025-08-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_devise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='paye_le',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
