# Generated by Django 5.2.5 on 2025-11-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_utilisateur_nom_utilisateur_prenom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='longitude',
        ),
        migrations.AddField(
            model_name='demande',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
